import type { ComponentMeta } from "./types";

/**
 * Catalogo metadata della Lumino Lab Library.
 *
 * Chiave = "categoria/slug-componente" (combacia con la struttura cartelle).
 * status:
 *   - "ready"        → codice TSX completo già raccolto (nella chat strategica),
 *                      pronto da salvare nel relativo file .tsx della cartella
 *   - "needs-fix"    → raccolto ma richiede adattamenti prima dell'uso
 *   - "missing-code" → solo nome + fonte: codice ancora da recuperare
 *
 * Conteggio: 100 componenti certificati (safe:true + status:ready + propsSchema + loader in render.tsx),
 * più 1 legacy "ready" non-safe (form/contact-2). Zero "missing-code". Catalogo chiuso.
 */
export const LUMINO_LIBRARY: Record<string, ComponentMeta> = {
  /* ─── 1. HERO (10) ───────────────────────────────────────────────── */
  "hero/pixel-hero": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      title: "string (required) — titolo principale",
      subtitle: "string (optional)",
      description: "string (optional)",
      primaryCta: "{ label: string, href?: string } (optional)",
      secondaryCta: "{ label: string, href?: string } (optional)",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional) — il canvas pixel usa accent+muted+ink",
      layout: "'centered' | 'left' (optional, default 'centered')",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal') — compact = griglia pixel più densa",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
    },
    name: "Pixel Hero",
    description: "Hero premium con canvas pixel art animato e tahoe glass text",
    tier: "premium",
    business: ["agenzia", "fashion", "hotel"],
    dependencies: ["lucide-react"],
    category: "hero",
    status: "ready",
  },
  "hero/preview-switch-hero": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      title: "string (required) — titolo principale",
      description: "string (optional)",
      primaryCta: "{ label: string, href?: string } (optional)",
      secondaryCta: "{ label: string, href?: string } (optional)",
      tabs: "Array<{ id: string, label: string, media: { src: string, alt: string } }> (required, >=1) — media = immagine anteprima (URL reale)",
      layout: "'standard' | 'compact' (optional, default 'standard')",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Preview Switch Hero",
    description: "Hero con switch anteprima live tra varianti",
    tier: "pro",
    business: ["saas", "agenzia", "all"],
    dependencies: ["framer-motion", "next"],
    category: "hero",
    status: "ready",
    notes: "21st.dev",
  },
  "hero/aurora-hero": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      title: "string (required) — titolo principale",
      subtitle: "string (optional) — occhiello sopra il titolo (accent)",
      description: "string (optional) — paragrafo introduttivo",
      primaryCta: "{ label: string, href?: string } (optional)",
      secondaryCta: "{ label: string, href?: string } (optional)",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional) — l'aurora usa accent+muted",
      layout: "'centered' | 'left' (optional, default 'centered')",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
    },
    name: "Aurora Hero",
    description: "Hero con sfondo aurora animato",
    tier: "pro",
    business: ["all"],
    dependencies: ["framer-motion"],
    category: "hero",
    status: "ready",
  },
  "hero/aether-hero": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      title: "string (required) — titolo principale",
      subtitle: "string (optional)",
      ctaLabel: "string (optional) — CTA primaria (usa accent)",
      ctaHref: "string (optional)",
      secondaryCtaLabel: "string (optional)",
      secondaryCtaHref: "string (optional)",
      align: "'left' | 'center' | 'right' (optional, default 'center')",
      maxWidth: "number (optional, default 960)",
      height: "string | number (optional, default '100vh')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Aether Hero",
    description: "Hero con shader WebGL a tutto schermo",
    tier: "premium",
    business: ["agenzia", "fashion", "fotografo"],
    dependencies: [],
    category: "hero",
    status: "ready",
    notes: "WebGL2 nativo",
  },
  "hero/halide-landing": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      title: "string (required) — titolo principale",
      subtitle: "string (optional)",
      eyebrow: "string (optional) — micro-testo in alto (accent, mono)",
      ctaLabel: "string (optional)",
      ctaHref: "string (optional)",
      images: "Array<{ src: string, alt: string }> (optional, fino a 3) — layer parallax (fallback gradient)",
      layout: "'editorial' | 'centered' (optional, default 'editorial')",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Halide Landing",
    description: "Hero editoriale minimale",
    tier: "all",
    business: ["fotografo", "fashion", "agenzia", "all"],
    dependencies: [],
    category: "hero",
    status: "ready",
    notes: "Editorial — parallax 3D",
  },
  "footer/site-footer": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      businessName: "string (required)",
      description: "string (optional)",
      logo: "{ src: string, alt: string } (optional)",
      columns: "Array<{ title: string, links: Array<{ label: string, href: string }> }> (optional)",
      socials: "Array<{ platform: string, url: string }> (optional) — platform = nome lucide (es. 'instagram')",
      address: "string (optional)",
      phone: "string (optional)",
      email: "string (optional)",
      copyright: "string (optional) — default '© {anno} {businessName}...'",
      newsletter: "{ enabled: boolean, action?: string } (optional) — form email + GDPR",
      legalLinks: "Array<{ label: string, href: string }> (optional)",
      layout: "'multi-column' | 'minimal' | 'centered' (optional, default 'multi-column')",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Site Footer",
    description: "Footer di chiusura multi-business: colonne link, social, contatti, newsletter con GDPR. Copyright in fondo.",
    tier: "all",
    business: ["all"],
    dependencies: ["lucide-react"],
    category: "footer",
    status: "ready",
  },

  /* ─── 2. FORM (1) ────────────────────────────────────────────────── */
  "form/contact-2": {
    name: "Contact 2",
    description: "Form di contatto base con campi essenziali",
    tier: "all",
    business: ["all"],
    dependencies: [],
    category: "form",
    status: "ready",
  },
  "form/contact": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      title: "string (optional, default 'Contattaci')",
      description: "string (optional)",
      phone: "string (optional) — info contatto",
      email: "string (optional) — info contatto",
      address: "string (optional) — info contatto",
      hours: "string (optional) — es. 'Lun-Ven 9:00-18:00'",
      mapsUrl: "string (optional) — se passato l'indirizzo diventa link",
      formAction: "string (optional, default '/api/contact') — endpoint POST",
      successMessage: "string (optional, default 'Grazie! Ti contatteremo presto.')",
      privacyUrl: "string (optional) — link Privacy Policy nel checkbox GDPR",
      layout: "'split' | 'centered' | 'stacked' (optional, default 'split')",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Contact",
    description: "Form contatti completo con info aziendali e checkbox GDPR obbligatoria. Multi-business.",
    tier: "all",
    business: ["all"],
    dependencies: ["framer-motion", "lucide-react"],
    category: "form",
    status: "ready",
  },

  /* ─── 4. PRICING (2) ─────────────────────────────────────────────── */
  "pricing/pricing-animated": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      title: "string (optional)",
      description: "string (optional)",
      plans: "Array<{ name: string, price: number, yearlyPrice: number, period: string, features: string[], description: string, buttonText: string, href: string, isPopular?: boolean }> (required, 2-4) — prezzi in €",
      layout: "'standard' | 'compact' (optional, default 'standard')",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Pricing Animated",
    description: "3 tier con confetti e numeri animati (NumberFlow)",
    tier: "pro",
    business: ["saas", "agenzia", "consulente", "all"],
    dependencies: ["framer-motion", "canvas-confetti", "@number-flow/react", "shadcn/ui"],
    category: "pricing",
    status: "ready",
  },
  "pricing/pricing-card-with-features": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      title: "string (required)",
      subtitle: "string (optional)",
      startingFrom: "boolean (optional) — mostra 'A partire da'",
      price: "number | string (required) — numero = € formattato",
      buttonText: "string (required)",
      buttonIcon: "string (optional) — nome icona lucide",
      href: "string (optional)",
      features: "Array<{ label: string, info?: string }> (required) — info = tooltip",
      layout: "'card' (optional)",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Pricing Card With Features",
    description: "Singolo tier con lista feature e tooltip",
    tier: "all",
    business: ["all"],
    dependencies: ["shadcn/ui", "react-icons"],
    category: "pricing",
    status: "ready",
  },

  /* ─── 5. TESTIMONIAL / RECENSIONI (4) ────────────────────────────── */
  "testimonial/case-studies": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      title: "string (required)",
      description: "string (optional)",
      studies: "Array<{ quote: string, name: string, role: string, image?: { src: string, alt: string }, icon?: string, metrics: Array<{ value: string, label: string, sub?: string }> }> (required, 1-3) — value es. '+250%' (numero animato)",
      layout: "'standard' | 'compact' (optional, default 'standard')",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Case Studies",
    description: "Layout zigzag con metriche CountUp",
    tier: "pro",
    business: ["agenzia", "saas", "consulente", "all"],
    dependencies: ["next", "lucide-react", "react-countup"],
    category: "testimonial",
    status: "ready",
  },
  "testimonial/client-feedback": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      title: "string (optional) — intestazione (no hardcoded)",
      description: "string (optional)",
      testimonials: "Array<{ quote: string, author: string, role?: string, accent?: boolean }> (required, 4-6)",
      layout: "'mosaic' | 'grid' | 'masonry' (optional, default 'mosaic')",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Client Feedback",
    description: "Griglia mosaico recensioni a 3 colonne",
    tier: "pro",
    business: ["all"],
    dependencies: ["next"],
    category: "testimonial",
    status: "ready",
    notes: "Richiede TimelineContent custom",
  },
  "testimonial/testimonial-carousel": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      testimonials: "Array<{ quote: string, author: string, role?: string, avatar?: { src: string, alt: string }, rating?: number }> (required, >=1) — recensioni",
      title: "string (optional) — intestazione (NON hardcoded, sempre via prop)",
      description: "string (optional)",
      autoplay: "boolean (optional, default false)",
      autoplayMs: "number (optional, default 5000)",
      layout: "'card' | 'split' | 'minimal' (optional, default 'card')",
      showRating: "boolean (optional, default true)",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Testimonial Carousel",
    description: "Card singola recensione in autoplay",
    tier: "pro",
    business: ["all"],
    dependencies: ["framer-motion", "lucide-react"],
    category: "testimonial",
    status: "ready",
  },
  "testimonial/masonry-grid": {
    safe: true,
    multiplicity: "wrapper",
    propsSchema: {
      columns: "number (optional, default 3)",
      gap: "number (optional, default 4) — gap in unità tailwind",
      children: "ReactNode (required) — le card vanno passate come children (wrapper, NON puro JSON)",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional)",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Masonry Grid",
    description: "Muro recensioni stile Instagram",
    tier: "pro",
    business: ["ristorante", "estetista", "fashion", "all"],
    dependencies: ["framer-motion"],
    category: "testimonial",
    status: "ready",
  },

  /* ─── 6. FEATURES / SHOWCASE (6) ─────────────────────────────────── */
  "features/feature-carousel": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      title: "string (optional)",
      description: "string (optional)",
      features: "Array<{ id: string, label: string, icon?: string, image: { src: string, alt: string }, description?: string }> (required, >=2) — icon = nome lucide",
      autoplay: "boolean (optional, default false)",
      autoplayMs: "number (optional, default 4000)",
      layout: "'split' | 'compact' (optional, default 'split')",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Feature Carousel",
    description: "Carosello feature split autoplay 40/60",
    tier: "pro",
    business: ["saas", "agenzia", "all"],
    dependencies: ["framer-motion", "hugeicons"],
    category: "features",
    status: "ready",
  },
  "features/features-section": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      title: "string (required)",
      description: "string (optional)",
      features: "Array<{ title: string, description: string, animation?: string }> (required, 3-8)",
      layout: "'grid' (optional, default 'grid')",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Features Section",
    description: "3 bento animate",
    tier: "pro",
    business: ["all"],
    dependencies: ["framer-motion"],
    category: "features",
    status: "ready",
  },
  "features/feature-highlight": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      title: "string (required) — titolo sezione",
      icon: "string (optional) — nome icona lucide della sezione (es. 'ShieldCheck')",
      features: "string[] (required) — i punti elencati con spunta",
      footer: "string (optional) — nota finale",
      layout: "'card' | 'inline' (optional, default 'card')",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Feature Highlight",
    description: "Lista feature con icone inline",
    tier: "pro",
    business: ["all"],
    dependencies: ["framer-motion", "lucide-react"],
    category: "features",
    status: "ready",
  },
  "features/features-cards-shader": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      title: "string (optional)",
      description: "string (optional)",
      features: "Array<{ title: string, description: string, icon?: string }> (required, 3-6) — icon = nome lucide",
      layout: "'grid' (optional, default 'grid')",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional) — colora lo shader",
    },
    name: "Features Cards Shader",
    description: "6 card con shader animato",
    tier: "premium",
    business: ["agenzia", "saas", "fashion"],
    dependencies: ["@paper-design/shaders-react"],
    category: "features",
    status: "ready",
  },
  "features/cybernetic-bento-grid": {
    safe: true,
    multiplicity: "single",
    hardcoded: true,
    propsSchema: {},
    name: "Cybernetic Bento Grid",
    description: "Bento con spotlight hover",
    tier: "pro",
    business: ["saas", "agenzia", "all"],
    dependencies: [],
    category: "features",
    status: "ready",
    notes: "Richiede CSS aggiuntivo — React only",
  },
  "features/feature-section": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      title: "string (required, default 'Cosa offriamo')",
      description: "string (optional)",
      highlight: "string (optional) — frase corta in evidenza (accent)",
      features: "Array<{ title: string, subtitle?: string, icon?: string }> (required, 3-12) — icon = nome lucide-react (es. 'Bell', 'Star')",
      tags: "string[] (optional) — badge",
      layout: "'autoscroll' | 'grid' | 'list' (optional, default 'autoscroll')",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Feature Section",
    description: "Sezione 'Cosa offriamo' flessibile: feature configurabili, icone lucide per nome, layout autoscroll/grid/list",
    tier: "pro",
    business: ["all"],
    dependencies: ["framer-motion", "lucide-react"],
    category: "features",
    status: "ready",
  },

  /* ─── 7. BOOKING / PRENOTAZIONI (2) ──────────────────────────────── */
  "booking/calendar": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      title: "string (optional, default 'Prenota un appuntamento')",
      description: "string (optional, default 'Domande sul nostro servizio?')",
      buttonText: "string (optional, default 'Prenota ora')",
      bookingUrl: "string (optional) — link Calendly/Cal.com del cliente (apre in nuova tab)",
      contactPhone: "string (optional) — fallback CTA 'Chiama' (tel:)",
      contactEmail: "string (optional)",
      duration: "string (optional, default '30 minuti')",
      availableDays: "string[] (optional, default lun-ven) — giorni aperti tra ['lun','mar','mer','gio','ven','sab','dom']",
      closedMessage: "string (optional) — es. 'Chiuso il lunedì'",
      layout: "'card' | 'split' | 'minimal' (optional, default 'card')",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Calendar",
    description: "Sezione prenotazione: mese corrente con giorni disponibili evidenziati, CTA intelligente (booking esterno / telefono / scroll a #contact)",
    tier: "pro",
    business: ["ristorante", "barbiere", "dentista", "estetista", "studio-medico", "hotel", "all"],
    dependencies: ["framer-motion"],
    category: "booking",
    status: "ready",
  },
  "booking/visualize-booking": {
    safe: true,
    multiplicity: "single",
    hardcoded: true,
    propsSchema: {},
    name: "Visualize Booking",
    description: "Dashboard appuntamenti",
    tier: "pro",
    business: ["barbiere", "dentista", "estetista", "studio-medico", "palestra", "all"],
    dependencies: ["lucide-react", "framer-motion"],
    category: "booking",
    status: "ready",
  },

  /* ─── 8. TICKET / RICEVUTE (1) ───────────────────────────────────── */
  "ticket/animated-ticket": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      ticketId: "string (required) — codice ricevuta",
      amount: "number (required) — importo in € (formattato automaticamente)",
      itemName: "string (required) — cosa rappresenta (es. 'Prenotazione tavolo')",
      businessName: "string (optional, default 'Lumino')",
      date: "string (optional) — data/ora già formattata o ISO",
      paymentMethod: "string (optional) — es. 'Contanti', 'Bonifico', 'Acconto'",
      cardLast4: "string (optional) — ultime 4 cifre (solo carta)",
      qrValue: "string (optional) — valore → barcode decorativo",
      confetti: "boolean (optional, default false) — coriandoli all'ingresso",
      layout: "'standard' | 'compact' | 'business' (optional, default 'standard')",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Animated Ticket",
    description: "Ricevuta animata con barcode e confetti",
    tier: "pro",
    business: ["ristorante", "hotel", "palestra", "all"],
    dependencies: [],
    category: "ticket",
    status: "ready",
    notes: "React/CSS puro",
  },

  /* ─── 9. TEXT ANIMATIONS (15) ────────────────────────────────────── */
  "text-animations/split-text": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      text: "string (required)",
      delay: "number (optional, default 0) — ritardo iniziale (s)",
      stagger: "number (optional, default 0.03) — ritardo tra lettere (s)",
      className: "string (optional)",
    },
    name: "Split Text",
    description: "Testo che appare lettera per lettera allo scroll",
    tier: "all",
    business: ["all"],
    dependencies: ["framer-motion"],
    category: "text-animations",
    status: "ready",
  },
  "text-animations/blur-text": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      text: "string (required)",
      delay: "number (optional, default 0)",
      className: "string (optional)",
    },
    name: "Blur Text",
    description: "Testo che appare da sfocato a nitido",
    tier: "all",
    business: ["all"],
    dependencies: ["framer-motion"],
    category: "text-animations",
    status: "ready",
  },
  "text-animations/shuffle-text": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      text: "string (required)",
      iterations: "number (optional, default 10)",
      speed: "number (optional, default 30) — ms per frame",
      className: "string (optional)",
    },
    name: "Shuffle Text",
    description: "Le lettere si mescolano prima di comporre il testo",
    tier: "all",
    business: ["all"],
    dependencies: [],
    category: "text-animations",
    status: "ready",
  },
  "text-animations/text-type": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      text: "string (required)",
      speed: "number (optional, default 50) — ms per carattere",
      cursor: "boolean (optional, default true)",
      className: "string (optional)",
    },
    name: "Text Type",
    description: "Effetto macchina da scrivere",
    tier: "all",
    business: ["all"],
    dependencies: [],
    category: "text-animations",
    status: "ready",
  },
  "text-animations/text-pressure": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      text: "string (required)",
      intensity: "number (optional, default 0.82) — schiacciamento",
      color: "string (optional)",
      className: "string (optional)",
    },
    name: "Text Pressure",
    description: "Il testo si schiaccia mentre lo premi",
    tier: "all",
    business: ["agenzia", "fashion", "all"],
    dependencies: [],
    category: "text-animations",
    status: "ready",
  },
  "text-animations/circular-text": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      text: "string (required)",
      radius: "number (optional, default 100) — px",
      spin: "boolean (optional, default false)",
      className: "string (optional)",
    },
    name: "Circular Text",
    description: "Testo disposto su un cerchio",
    tier: "all",
    business: ["all"],
    dependencies: [],
    category: "text-animations",
    status: "ready",
  },
  "text-animations/curved-loop": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      text: "string (required)",
      speed: "number (optional, default 12) — secondi per ciclo",
      curve: "number (optional, default 40) — curvatura",
      className: "string (optional)",
    },
    name: "Curved Loop",
    description: "Testo in loop su tracciato curvo (SVG)",
    tier: "all",
    business: ["all"],
    dependencies: [],
    category: "text-animations",
    status: "ready",
  },
  "text-animations/decrypted-text": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      text: "string (required)",
      speed: "number (optional, default 30) — ms per frame",
      characters: "string (optional) — set di caratteri",
      className: "string (optional)",
    },
    name: "Decrypted Text",
    description: "Effetto decrittazione del testo",
    tier: "all",
    business: ["saas", "agenzia", "all"],
    dependencies: [],
    category: "text-animations",
    status: "ready",
  },
  "text-animations/scroll-reveal": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      text: "string (required)",
      threshold: "number (optional, default 0.3) — soglia viewport",
      stagger: "number (optional, default 0.04) — ritardo tra parole",
      className: "string (optional)",
    },
    name: "Scroll Reveal",
    description: "Testo rivelato parola per parola allo scroll",
    tier: "all",
    business: ["all"],
    dependencies: ["framer-motion"],
    category: "text-animations",
    status: "ready",
  },
  "text-animations/rotating-text": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      words: "string[] (required) — parole da alternare",
      interval: "number (optional, default 2000) — ms",
      animation: "'fade' | 'slide' | 'spin' (optional, default 'fade')",
      className: "string (optional)",
    },
    name: "Rotating Text",
    description: "Parole che si alternano in sequenza",
    tier: "all",
    business: ["all"],
    dependencies: ["framer-motion"],
    category: "text-animations",
    status: "ready",
  },
  "text-animations/scroll-float": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      text: "string (required)",
      intensity: "number (optional, default 20) — px di fluttuazione",
      className: "string (optional)",
    },
    name: "Scroll Float",
    description: "Testo che fluttua durante lo scroll",
    tier: "all",
    business: ["all"],
    dependencies: ["framer-motion"],
    category: "text-animations",
    status: "ready",
  },
  "text-animations/scroll-velocity": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      text: "string (required)",
      velocity: "number (optional, default 1) — moltiplicatore",
      className: "string (optional)",
    },
    name: "Scroll Velocity",
    description: "Testo che scorre in base alla velocità di scroll",
    tier: "all",
    business: ["all"],
    dependencies: ["framer-motion"],
    category: "text-animations",
    status: "ready",
  },
  "text-animations/variable-proximity": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      text: "string (required)",
      radius: "number (optional, default 100) — px raggio di influenza",
      className: "string (optional)",
    },
    name: "Variable Proximity",
    description: "Il peso del font cambia con la distanza del mouse",
    tier: "all",
    business: ["agenzia", "fashion", "all"],
    dependencies: [],
    category: "text-animations",
    status: "ready",
  },
  "text-animations/count-up": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      end: "number (required) — valore finale",
      duration: "number (optional, default 1.8)",
      prefix: "string (optional)",
      suffix: "string (optional)",
      decimals: "number (optional, default 0)",
      className: "string (optional)",
    },
    name: "Count Up",
    description: "Conteggio numerico animato allo scroll (react-countup)",
    tier: "all",
    business: ["all"],
    dependencies: ["react-countup"],
    category: "text-animations",
    status: "ready",
  },
  "text-animations/text-hover-effect": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      text: "string (required)",
      color: "string (optional, default accent)",
      className: "string (optional)",
    },
    name: "Text Hover Effect",
    description: "Riempimento del testo (outline → fill) all'hover",
    tier: "all",
    business: ["agenzia", "fashion", "all"],
    dependencies: [],
    category: "text-animations",
    status: "ready",
  },

  /* ─── 10. HOVER EFFECTS & CARD (7) ───────────────────────────────── */
  "hover-effects/pixel-transition": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      children: "ReactNode (required)",
      pixelSize: "number (optional, default 24)",
      color: "string (optional, default accent)",
      className: "string (optional)",
    },
    name: "Pixel Transition",
    description: "Overlay a pixel che appare all'hover (wrapper)",
    tier: "all",
    business: ["all"],
    dependencies: [],
    category: "hover-effects",
    status: "ready",
  },
  "hover-effects/glare-hover": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      children: "ReactNode (required)",
      color: "string (optional)",
      intensity: "number (optional, default 0.4)",
      className: "string (optional)",
    },
    name: "Glare Hover",
    description: "Riflesso luminoso che segue il cursore (wrapper)",
    tier: "all",
    business: ["all"],
    dependencies: [],
    category: "hover-effects",
    status: "ready",
  },
  "hover-effects/star-border": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      children: "ReactNode (required)",
      color: "string (optional, default accent)",
      speed: "number (optional, default 6) — secondi per giro",
      className: "string (optional)",
    },
    name: "Star Border",
    description: "Bordo con gradiente animato rotante (wrapper)",
    tier: "all",
    business: ["all"],
    dependencies: [],
    category: "hover-effects",
    status: "ready",
  },
  "hover-effects/electric-border": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      children: "ReactNode (required)",
      color: "string (optional, default accent)",
      speed: "number (optional, default 3) — secondi per giro",
      className: "string (optional)",
    },
    name: "Electric Border",
    description: "Bordo con gradiente animato elettrico (wrapper)",
    tier: "pro",
    business: ["agenzia", "saas", "all"],
    dependencies: [],
    category: "hover-effects",
    status: "ready",
  },
  "hover-effects/magnet": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      children: "ReactNode (required)",
      strength: "number (optional, default 0.5) — forza di attrazione",
      className: "string (optional)",
    },
    name: "Magnet",
    description: "L'elemento viene attratto verso il cursore (wrapper)",
    tier: "all",
    business: ["all"],
    dependencies: [],
    category: "hover-effects",
    status: "ready",
  },
  "hover-effects/tilted-card": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      children: "ReactNode (required)",
      intensity: "number (optional, default 12) — gradi di inclinazione",
      className: "string (optional)",
    },
    name: "Tilted Card",
    description: "Card che si inclina seguendo il mouse (wrapper)",
    tier: "pro",
    business: ["all"],
    dependencies: [],
    category: "hover-effects",
    status: "ready",
  },
  "hover-effects/card-3d": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      children: "ReactNode (required)",
      intensity: "number (optional, default 15) — gradi rotazione",
      className: "string (optional)",
    },
    name: "3D Card",
    description: "Card che ruota in 3D seguendo il mouse (wrapper)",
    tier: "pro",
    business: ["all"],
    dependencies: [],
    category: "hover-effects",
    status: "ready",
  },

  /* ─── 11. GALLERY & MOVIMENTO (8) ────────────────────────────────── */
  "gallery/orbit-images": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      images: "Array<{ src: string, alt: string }> (required) — immagini in orbita",
      radius: "number (optional, default 180) — raggio orbita in px",
      speed: "number (optional, default 20) — secondi per giro",
      color: "string (optional)",
    },
    name: "Orbit Images",
    description: "Immagini in orbita attorno a un centro",
    tier: "premium",
    business: ["fashion", "fotografo", "agenzia"],
    dependencies: [],
    category: "gallery",
    status: "ready",
  },
  "gallery/logo-loop": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      logos: "Array<{ src: string, alt: string, name?: string }> (required)",
      speed: "number (optional, default 25) — secondi per ciclo",
      direction: "'left' | 'right' (optional, default 'left')",
    },
    name: "Logo Loop",
    description: "Loop infinito di loghi",
    tier: "all",
    business: ["agenzia", "saas", "consulente", "all"],
    dependencies: [],
    category: "gallery",
    status: "ready",
  },
  "gallery/image-trail": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      images: "Array<{ src: string, alt: string }> (required)",
      trailLength: "number (optional, default 5) — numero immagini nella scia",
    },
    name: "Image Trail",
    description: "Scia di immagini che segue il cursore",
    tier: "premium",
    business: ["fashion", "fotografo", "agenzia"],
    dependencies: ["framer-motion"],
    category: "gallery",
    status: "ready",
  },
  "gallery/circular-gallery": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      images: "Array<{ src: string, alt: string, caption?: string }> (required)",
      autoRotate: "boolean (optional, default false)",
    },
    name: "Circular Gallery",
    description: "Galleria circolare scorrevole (coverflow)",
    tier: "premium",
    business: ["fashion", "fotografo", "hotel"],
    dependencies: ["framer-motion", "lucide-react"],
    category: "gallery",
    status: "ready",
  },
  "gallery/stack-gallery": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      images: "Array<{ src: string, alt: string, title?: string }> (required)",
      onSwipe: "(index: number) => void (optional)",
    },
    name: "Stack Gallery",
    description: "Stack di card sfogliabili (drag/swipe)",
    tier: "pro",
    business: ["all"],
    dependencies: ["framer-motion"],
    category: "gallery",
    status: "ready",
  },
  "gallery/masonry-images": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      images: "Array<{ src: string, alt: string, aspect?: number }> (required)",
      columns: "number (optional, default 3)",
    },
    name: "Masonry Images",
    description: "Griglia masonry di immagini (colonne CSS). Diverso da masonry-grid (wrapper).",
    tier: "pro",
    business: ["ristorante", "fashion", "fotografo", "all"],
    dependencies: ["framer-motion"],
    category: "gallery",
    status: "ready",
  },
  "gallery/dome-gallery": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      images: "Array<{ src: string, alt: string }> (required, max ~12)",
      autoRotate: "boolean (optional, default true)",
    },
    name: "Dome Gallery",
    description: "Galleria a cupola 3D immersiva",
    tier: "premium",
    business: ["fashion", "fotografo", "hotel"],
    dependencies: ["@react-three/fiber", "@react-three/drei", "three"],
    category: "gallery",
    status: "ready",
  },
  "gallery/marquee": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      images: "Array<{ src: string, alt: string }> (required)",
      speed: "number (optional, default 30) — secondi per ciclo",
      direction: "'left' | 'right' (optional, default 'left')",
      className: "string (optional)",
    },
    name: "Marquee",
    description: "Loop infinito orizzontale di immagini (pausa su hover)",
    tier: "all",
    business: ["all"],
    dependencies: [],
    category: "gallery",
    status: "ready",
  },

  /* ─── 12. SCROLL ANIMATIONS (1) ──────────────────────────────────── */
  "scroll-animations/zoom-parallax": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      title: "string (optional)",
      description: "string (optional)",
      images: "Array<{ src: string, alt: string, caption?: string }> (required, 3-9)",
      maxScale: "number (optional, default 5) — zoom massimo",
      backgroundColor: "string (optional) — override sfondo",
      layout: "'standard' | 'fullscreen' (optional, default 'standard')",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Zoom Parallax",
    description: "7 immagini con zoom scroll-driven",
    tier: "pro",
    business: ["fashion", "fotografo", "hotel", "all"],
    dependencies: ["framer-motion", "lenis"],
    category: "scroll-animations",
    status: "ready",
    notes: "Lenis opzionale",
  },

  /* ─── 13. BACKGROUNDS & EFFETTI VISIVI (5) ───────────────────────── */
  "backgrounds/magic-rings": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      color: "string (optional) — default accent",
      ringsCount: "number (optional, default 5)",
      speed: "number (optional, default 8) — secondi",
    },
    name: "Magic Rings",
    description: "Sfondo con anelli concentrici animati (decorativo, assoluto)",
    wowType: "background",
    wowLevel: "medium",
    tier: "pro",
    business: ["agenzia", "saas", "all"],
    dependencies: [],
    category: "backgrounds",
    status: "ready",
  },
  "backgrounds/laser-flow": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      color: "string (optional) — default accent",
      intensity: "number (optional, default 0.6) — opacità 0..1",
      direction: "'horizontal' | 'vertical' | 'diagonal' (optional, default 'diagonal')",
    },
    name: "Laser Flow",
    description: "Sfondo con fasci laser in movimento (decorativo, assoluto)",
    wowType: "background",
    wowLevel: "premium",
    tier: "premium",
    business: ["agenzia", "saas", "fashion"],
    dependencies: [],
    category: "backgrounds",
    status: "ready",
  },
  "backgrounds/magnet-lines": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      color: "string (optional) — default accent",
      density: "number (optional, default 12) — linee per lato della griglia",
    },
    name: "Magnet Lines",
    description: "Griglia di linee che si orientano verso il cursore (magnete)",
    tier: "pro",
    business: ["agenzia", "saas", "all"],
    dependencies: [],
    category: "backgrounds",
    status: "ready",
  },
  "backgrounds/gradual-blur": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      direction: "'top' | 'bottom' | 'left' | 'right' (optional, default 'bottom')",
      intensity: "number (optional, default 1) — moltiplicatore forza blur",
    },
    name: "Gradual Blur",
    description: "Overlay con blur/sfumatura progressiva su un bordo (decorativo)",
    wowType: "background",
    wowLevel: "basic",
    tier: "all",
    business: ["all"],
    dependencies: [],
    category: "backgrounds",
    status: "ready",
  },

  /* ─── 14. STRUCTURAL (4) ─────────────────────────────────────────── */
  "structural/animated-list": {
    safe: true,
    multiplicity: "wrapper",
    propsSchema: {
      items: "Array<ReactNode> (required) — wrapper, NON puro JSON",
      stagger: "number (optional, default 0.05) — secondi tra item",
    },
    name: "Animated List",
    description: "Lista con elementi animati in entrata (stagger allo scroll)",
    tier: "pro",
    business: ["all"],
    dependencies: ["framer-motion"],
    category: "structural",
    status: "ready",
  },
  "structural/scroll-stack": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      cards: "Array<{ title: string, description: string, image?: string }> (required)",
    },
    name: "Scroll Stack",
    description: "Card che si impilano allo scroll (sticky stacking)",
    tier: "pro",
    business: ["all"],
    dependencies: ["framer-motion"],
    category: "structural",
    status: "ready",
  },
  "structural/magic-bento": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      items: "Array<{ title: string, description: string, icon?: string, size?: 'sm' | 'md' | 'lg' }> (required) — icon = nome lucide",
    },
    name: "Magic Bento",
    description: "Griglia bento premium con spotlight/glow su hover",
    tier: "pro",
    business: ["saas", "agenzia", "all"],
    dependencies: ["framer-motion", "lucide-react"],
    category: "structural",
    status: "ready",
  },
  "scroll-animations/container-scroll": {
    safe: true,
    multiplicity: "wrapper",
    propsSchema: {
      title: "ReactNode (optional) — titolo (slot) sopra il riquadro",
      children: "ReactNode (required) — contenuto dentro il riquadro 3D (wrapper, NON puro JSON)",
      perspective: "number (optional, default 1000)",
      rotateStart: "number (optional, default 20) — inclinazione iniziale in gradi",
      layout: "'standard' | 'compact' (optional, default 'standard')",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Container Scroll",
    description: "Contenitore con rotazione 3D allo scroll",
    tier: "pro",
    business: ["saas", "agenzia", "all"],
    dependencies: ["framer-motion"],
    category: "scroll-animations",
    status: "ready",
    notes: "Aceternity",
  },

  /* ─── 15. NAVIGATION (4) ─────────────────────────────────────────── */
  "navigation/bubble-menu": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      links: "Array<{ label: string, href: string }> (required)",
      position: "'top' | 'bottom' (optional, default 'bottom')",
    },
    name: "Bubble Menu",
    description: "Menu a bolle animato (FAB che espande i link)",
    tier: "pro",
    business: ["all"],
    dependencies: ["framer-motion", "lucide-react"],
    category: "navigation",
    status: "ready",
  },
  "navigation/card-nav": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      items: "Array<{ label: string, href: string, preview?: { image?: string, description?: string } }> (required)",
    },
    name: "Card Nav",
    description: "Navigazione con card di anteprima su hover",
    tier: "pro",
    business: ["all"],
    dependencies: ["framer-motion"],
    category: "navigation",
    status: "ready",
  },
  "navigation/pill-nav": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      links: "Array<{ label: string, href: string }> (required)",
      activeIndex: "number (optional, default 0)",
    },
    name: "Pill Nav",
    description: "Navbar a pillola con indicatore animato (layoutId)",
    tier: "all",
    business: ["all"],
    dependencies: ["framer-motion"],
    category: "navigation",
    status: "ready",
  },
  "navigation/staggered-menu": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      links: "Array<{ label: string, href: string }> (required)",
      ctaButton: "{ label: string, href: string } (optional)",
    },
    name: "Staggered Menu",
    description: "Menu fullscreen con apertura staggered dei link",
    tier: "pro",
    business: ["all"],
    dependencies: ["framer-motion", "lucide-react"],
    category: "navigation",
    status: "ready",
  },

  /* ─── 16. PREMIUM 3D / WEBGL (6) ─────────────────────────────────── */
  "premium-3d/antigravity": {
    safe: true,
    multiplicity: "wrapper",
    propsSchema: {
      items: "Array<ReactNode> (required) — wrapper, NON puro JSON",
      intensity: "number (optional, default 1) — ampiezza fluttuazione",
    },
    name: "Antigravity",
    description: "Elementi che fluttuano dolcemente (levitazione, framer-motion)",
    tier: "premium",
    business: ["agenzia", "saas", "fashion"],
    dependencies: ["framer-motion"],
    category: "premium-3d",
    status: "ready",
  },
  "premium-3d/globe-3d": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      pins: "Array<{ lat: number, lng: number, label?: string }> (required)",
      autoRotate: "boolean (optional, default true)",
      color: "string (optional) — default accent",
    },
    name: "Globe 3D",
    description: "Globo 3D rotante con pin geolocalizzati",
    tier: "premium",
    business: ["saas", "agenzia", "consulente"],
    dependencies: ["@react-three/fiber", "three"],
    category: "premium-3d",
    status: "ready",
  },
  "premium-3d/ribbons": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      colors: "string[] (optional) — default accent + varianti",
      count: "number (optional, default 3) — numero nastri",
    },
    name: "Ribbons",
    description: "Nastri fluidi che ondeggiano (SVG + framer-motion, decorativo)",
    tier: "premium",
    business: ["agenzia", "fashion", "fotografo"],
    dependencies: ["framer-motion"],
    category: "premium-3d",
    status: "ready",
  },
  "premium-3d/splash-cursor": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      color: "string (optional) — default accent",
      viscosity: "number (optional, default 0.5) — 0..1 persistenza scia",
    },
    name: "Splash Cursor",
    description: "Splash fluido che segue il cursore (overlay decorativo)",
    tier: "premium",
    business: ["agenzia", "fashion", "all"],
    dependencies: [],
    category: "premium-3d",
    status: "ready",
  },
  "premium-3d/fluid-glass": {
    safe: true,
    multiplicity: "wrapper",
    propsSchema: {
      children: "ReactNode (required) — wrapper, NON puro JSON",
      distortion: "number (optional, default 1)",
      color: "string (optional) — default accent",
    },
    name: "Fluid Glass",
    description: "Pannello vetro fluido animato (glassmorphism) che avvolge children",
    tier: "premium",
    business: ["agenzia", "fashion", "hotel"],
    dependencies: ["framer-motion"],
    category: "premium-3d",
    status: "ready",
  },
  "premium-3d/particle-sphere": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      title: "string (optional)",
      images: "Array<{ src: string, alt: string }> (required, 4-8) — immagini in orbita",
      particleCount: "number (optional, default 1500)",
      sphereRadius: "number (optional, default 9)",
      autoRotate: "boolean (optional, default true)",
      layout: "'standard' | 'compact' (optional, default 'standard')",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Particle Sphere",
    description: "Sfera di particelle 3D interattiva",
    wowType: "3d",
    wowLevel: "premium",
    tier: "premium",
    business: ["agenzia", "saas", "fashion"],
    dependencies: ["three"],
    category: "premium-3d",
    status: "ready",
  },

  /* ─── 17. CURSORS (3) ────────────────────────────────────────────── */
  "cursors/target-cursor": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      color: "string (optional, default accent)",
      size: "number (optional, default 30)",
      className: "string (optional)",
    },
    name: "Target Cursor",
    description: "Cursore a mirino che segue il mouse (globale)",
    wowType: "cursor",
    wowLevel: "premium",
    tier: "premium",
    business: ["agenzia", "fashion", "all"],
    dependencies: [],
    category: "cursors",
    status: "ready",
  },
  "cursors/ghost-cursor": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      color: "string (optional, default accent)",
      trailLength: "number (optional, default 8)",
      className: "string (optional)",
    },
    name: "Ghost Cursor",
    description: "Cursore con scia di punti (globale)",
    wowType: "cursor",
    wowLevel: "premium",
    tier: "premium",
    business: ["agenzia", "fashion", "all"],
    dependencies: [],
    category: "cursors",
    status: "ready",
  },
  "cursors/blob-cursor": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      color: "string (optional, default accent)",
      size: "number (optional, default 40)",
      className: "string (optional)",
    },
    name: "Blob Cursor",
    description: "Cursore blob morbido con spring (globale)",
    wowType: "cursor",
    wowLevel: "premium",
    tier: "premium",
    business: ["agenzia", "fashion", "all"],
    dependencies: ["framer-motion"],
    category: "cursors",
    status: "ready",
  },

  /* ─── 18. MICRO-INTERAZIONI (1) ──────────────────────────────────── */
  "micro-interactions/click-spark": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      children: "ReactNode (required)",
      color: "string (optional, default accent)",
      particleCount: "number (optional, default 8)",
      className: "string (optional)",
    },
    name: "Click Spark",
    description: "Particelle al click sull'area (wrapper)",
    tier: "all",
    business: ["all"],
    dependencies: [],
    category: "micro-interactions",
    status: "ready",
  },

  /* ─── 19. BADGE / ANNOUNCEMENT (1) ───────────────────────────────── */
  "badge/announcement": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      variant: "'default' | 'secondary' | 'outline' (optional, default 'outline')",
      themed: "boolean (optional) — usa l'accent della palette per bordo/testo",
      children: "ReactNode (required) — comporre con <AnnouncementTag> + <AnnouncementTitle>",
    },
    name: "Announcement",
    description: "Pill annuncio con tag",
    tier: "all",
    business: ["all"],
    dependencies: ["shadcn/ui"],
    category: "badge",
    status: "ready",
    notes: "shadcn-based",
  },

  /* ─── 20. SPECIAL (3) ────────────────────────────────────────────── */
  "special/true-focus": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      children: "ReactNode (required) — gli elementi tra cui mettere a fuoco",
      intensity: "number (optional, default 4) — blur degli altri (px)",
      className: "string (optional)",
    },
    name: "True Focus",
    description: "Sfoca gli altri elementi tranne quello sotto il mouse (wrapper)",
    tier: "pro",
    business: ["agenzia", "all"],
    dependencies: [],
    category: "special",
    status: "ready",
  },
  "special/shape-blur": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      shapes: "Array<{ type: 'circle' | 'blob' | 'square', color: string, size: number }> (required)",
      blur: "number (optional, default 80) — px di blur",
    },
    name: "Shape Blur",
    description: "Forme colorate sfocate che fluttuano (decorativo, CSS + framer-motion)",
    tier: "premium",
    business: ["agenzia", "fashion", "all"],
    dependencies: ["framer-motion"],
    category: "special",
    status: "ready",
  },
  "special/text-flipping-board": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      text: "string (required)",
      speed: "number (optional, default 100) — ms per step di flip",
    },
    name: "Text Flipping Board",
    description: "Tabellone split-flap stile aeroporto/Solari",
    tier: "pro",
    business: ["hotel", "ristorante", "all"],
    dependencies: ["framer-motion"],
    category: "special",
    status: "ready",
  },

  /* ─── 21. CONTAINER / SURFACE (1) ────────────────────────────────── */
  "container/glass-surface": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      children: "ReactNode (required)",
      blur: "number (optional, default 12)",
      opacity: "number (optional, default 0.12)",
      border: "boolean (optional, default true)",
      className: "string (optional)",
    },
    name: "Glass Surface",
    description: "Superficie glassmorphism riutilizzabile (wrapper)",
    tier: "pro",
    business: ["all"],
    dependencies: [],
    category: "container",
    status: "ready",
  },
  "micro-interactions/sparkle-trail": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      color: "string (optional, default accent)",
      particleCount: "number (optional, default 12)",
      className: "string (optional)",
    },
    name: "Sparkle Trail",
    description: "Particelle che seguono il mouse e svaniscono (globale)",
    tier: "all",
    business: ["all"],
    dependencies: [],
    category: "micro-interactions",
    status: "ready",
  },
  "micro-interactions/copy-button": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      text: "string (required) — testo da copiare negli appunti",
      label: "string (optional, default 'Copia')",
    },
    name: "Copy Button",
    description: "Pulsante che copia un testo negli appunti con feedback 'Copiato!'",
    tier: "all",
    business: ["all"],
    dependencies: ["lucide-react", "framer-motion"],
    category: "micro-interactions",
    status: "ready",
  },
  "micro-interactions/scroll-progress": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      color: "string (optional, default accent)",
      height: "number (optional, default 3) — px",
    },
    name: "Scroll Progress",
    description: "Barra di avanzamento dello scroll della pagina, fissa in alto",
    tier: "all",
    business: ["all"],
    dependencies: ["framer-motion"],
    category: "micro-interactions",
    status: "ready",
  },
  "badge/tag-list": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      tags: "Array<{ label: string, color?: string }> (required)",
      removable: "boolean (optional) — mostra X per rimuovere",
    },
    name: "Tag List",
    description: "Lista di tag/chip inline, opzionalmente rimovibili",
    tier: "all",
    business: ["all"],
    dependencies: ["framer-motion", "lucide-react"],
    category: "badge",
    status: "ready",
  },

  /* ─── 22. DASHBOARD CLIENTE UI (2) ───────────────────────────────── */
  "dashboard-ui/table-toolbar": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      title: "string (optional)",
      search: "boolean (optional) — mostra input di ricerca",
      filters: "Array<{ label: string, options: string[] }> (optional)",
      actions: "Array<{ label: string, onClick?: () => void }> (optional)",
    },
    name: "Table Toolbar",
    description: "Toolbar per tabelle (titolo, ricerca, filtri, azioni)",
    tier: "all",
    business: ["all"],
    dependencies: ["lucide-react"],
    category: "dashboard-ui",
    status: "ready",
  },
  "dashboard-ui/notch": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      status: "'online' | 'offline' | 'busy' (optional, default 'online')",
      label: "string (optional)",
    },
    name: "Notch",
    description: "Indicatore di stato stile Dynamic Island con dot + label",
    tier: "pro",
    business: ["all"],
    dependencies: ["framer-motion"],
    category: "dashboard-ui",
    status: "ready",
  },

  /* ─── 23. PATTERN UI RIUTILIZZABILI (1) ──────────────────────────── */
  "patterns/grid-modal-detail": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      title: "string (optional)",
      modalTitle: "string (optional) — titolo del modale (default = nome voce)",
      items: "Array<{ id: string, name: string, description?: string, badges?: string[], meta?: Record<string, string|number> }> (required)",
      columns: "number (optional, default 3)",
      showSearch: "boolean (optional, default false) — barra di ricerca",
      layout: "'grid' | 'list' (optional, default 'grid')",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Grid Modal Detail",
    description:
      "Pattern griglia card + modal dettaglio (ex AiModelsList) riutilizzabile per servizi/team/menu. ATTENZIONE: NON usare per menu di ristoranti (usa menu/menu-item-card). Usa solo per liste di servizi, modelli, prodotti astratti con descrizione lunga.",
    tier: "pro",
    business: ["all"],
    dependencies: ["framer-motion"],
    category: "patterns",
    status: "ready",
  },

  /* ─── BUCHI DA RIEMPIRE — status missing-code (4) ────────────────── */
  "menu/menu-item-card": {
    safe: true,
    multiplicity: "collection",
    propsSchema: {
      name: "string (required) — nome piatto/servizio",
      description: "string (optional) — descrizione breve",
      price: "number (required) — prezzo in €",
      originalPrice: "number (optional) — se > price mostra lo sconto",
      image: "{ src: string, alt: string } (optional) — URL Unsplash reale",
      isVegetarian: "boolean (optional)",
      isVegan: "boolean (optional)",
      isGlutenFree: "boolean (optional)",
      isSpicy: "boolean (optional)",
      allergens: "string[] (optional) — riga 'Allergeni: ...'",
      prepTime: "number (optional) — minuti",
      featured: "boolean (optional) — bordo accent + label 'Specialità'",
      layout: "'card' | 'list' | 'minimal' (optional, default 'card')",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Menu Item Card",
    description: "Card per singolo piatto del menu di un ristorante con foto, prezzo, sconto e tempo preparazione. USA QUESTO per qualsiasi voce di menu in un ristorante (mai grid-modal-detail per i menu).",
    tier: "all",
    business: ["ristorante", "all"],
    dependencies: [],
    category: "menu",
    status: "ready",
    notes: "Prezzi in ₹ da cambiare in €",
  },
  "about/about-3": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      title: "string (required) — titolo sezione (es. 'Chi siamo')",
      description: "string (optional) — paragrafo introduttivo",
      mainImage: "{ src: string, alt: string } (optional) — fallback gradient se assente",
      secondaryImage: "{ src: string, alt: string } (optional)",
      breakout: "{ title: string, description: string, buttonText?: string, buttonUrl?: string } (optional) — riquadro highlight",
      companiesTitle: "string (optional, default 'Apprezzati da')",
      companies: "Array<{ name: string, logo?: string }> (optional) — senza logo mostra il NOME del brand in tipografia",
      achievementsTitle: "string (optional, default 'I nostri numeri')",
      achievementsDescription: "string (optional)",
      achievements: "Array<{ label: string, value: string }> (optional) — statistiche/numeri",
      layout: "'standard' | 'compact' | 'editorial' (optional, default 'standard')",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "About 3",
    description: "Sezione Chi siamo: split foto + storia + valori",
    tier: "all",
    business: ["all"],
    dependencies: [],
    category: "about",
    status: "ready",
  },
  "map/mapcn-map": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      title: "string (optional)",
      description: "string (optional)",
      locations: "Array<{ lat: number, lng: number, name: string, address?: string, phone?: string, hours?: string }> (required)",
      defaultZoom: "number (optional, default 13)",
      showRoute: "boolean (optional) — collega i punti con una linea",
      styleUrl: "string (optional) — stile MapLibre custom (altrimenti raster OSM)",
      layout: "'standard' | 'split' (optional, default 'standard')",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Mapcn Map",
    description: "Mappa interattiva MapLibre con i punti del business (marker, popup, route). Self-contained, nessuna API key (tile OSM).",
    tier: "pro",
    business: ["ristorante", "barbiere", "dentista", "hotel", "palestra", "estetista", "studio-medico", "all"],
    dependencies: ["maplibre-gl", "lucide-react"],
    category: "map",
    status: "ready",
    notes: "~400KB, lazy-load consigliato",
  },
  "product/product-card": {
    safe: true,
    multiplicity: "collection",
    propsSchema: {
      name: "string (required) — nome prodotto",
      description: "string (optional)",
      price: "number (required) — prezzo €",
      originalPrice: "number (optional) — se > price mostra lo sconto",
      image: "{ src: string, alt: string } (optional) — fallback gradient se assente",
      badges: "string[] (optional) — etichette in alto (es. 'Novità')",
      variants: "Array<{ color: string, label?: string }> (optional) — pallini colore",
      cta: "{ label: string, href?: string } (optional)",
      layout: "'card' | 'minimal' (optional, default 'card')",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Product Card",
    description: "Card prodotto e-commerce: foto, prezzo, CTA",
    tier: "all",
    business: ["fashion", "all"],
    dependencies: [],
    category: "product",
    status: "ready",
  },
  "hero/floating-food-hero": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      title: "string (required) — titolo principale",
      subtitle: "string (optional)",
      description: "string (optional)",
      primaryCta: "{ label: string, href?: string } (optional)",
      secondaryCta: "{ label: string, href?: string } (optional)",
      images: "Array<{ src: string, alt: string }> (optional) — foto piatti/locale, URL Unsplash reali (niente più className)",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
      layout: "'split' | 'centered' | 'grid' (optional, default 'split') — split=testo+griglia foto, centered=foto sfondo+overlay scuro, grid=testo sopra griglia 2x2",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern') — classic/editorial = titolo serif",
    },
    name: "Floating Food Hero",
    description: "Hero con immagini cibo fluttuanti e swirl decorativi",
    tier: "all",
    business: ["ristorante", "all"],
    dependencies: [],
    category: "hero",
    status: "ready",
  },
  /* ─── DECORATIVI / UTILITY (8 nuovi) ─────────────────────────────── */
  "backgrounds/grid-pattern": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      size: "number (optional, default 40) — passo griglia (px)",
      color: "string (optional, default muted)",
      opacity: "number (optional, default 0.4)",
      className: "string (optional)",
    },
    name: "Grid Pattern",
    description: "Sfondo a griglia sottile (decorativo, assoluto)",
    tier: "all", business: ["all"], dependencies: [], category: "backgrounds", status: "ready",
  },
  "backgrounds/dots-pattern": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      size: "number (optional, default 1.5) — raggio punto",
      gap: "number (optional, default 18) — distanza (px)",
      color: "string (optional, default muted)",
      opacity: "number (optional, default 0.5)",
      className: "string (optional)",
    },
    name: "Dots Pattern",
    description: "Sfondo a punti (decorativo, assoluto)",
    tier: "all", business: ["all"], dependencies: [], category: "backgrounds", status: "ready",
  },
  "backgrounds/aurora": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      colors: "string[] (optional, default accent+muted)",
      intensity: "number (optional, default 0.5) — opacità",
      className: "string (optional)",
    },
    name: "Aurora Background",
    description: "Gradiente animato decorativo riusabile (assoluto)",
    tier: "all", business: ["all"], dependencies: [], category: "backgrounds", status: "ready",
  },
  "gallery/image-grid": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      images: "Array<{ src: string, alt: string }> (required)",
      columns: "number (optional, default 3)",
      gap: "number (optional, default 4) — unità tailwind",
      className: "string (optional)",
    },
    name: "Image Grid",
    description: "Griglia responsive di immagini con fade-in",
    tier: "all", business: ["all"], dependencies: ["framer-motion"], category: "gallery", status: "ready",
  },
  "navigation/sticky-header": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      logo: "ReactNode (required) — testo o elemento",
      links: "Array<{ label: string, href: string }> (required)",
      cta: "{ label: string, href: string } (optional)",
      className: "string (optional)",
    },
    name: "Sticky Header",
    description: "Header che diventa solido allo scroll",
    tier: "all", business: ["all"], dependencies: [], category: "navigation", status: "ready",
  },
  "navigation/mobile-menu": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      links: "Array<{ label: string, href: string }> (required)",
      ctaButton: "{ label: string, href: string } (optional)",
      className: "string (optional)",
    },
    name: "Mobile Menu",
    description: "Menu hamburger fullscreen",
    tier: "all", business: ["all"], dependencies: ["framer-motion", "lucide-react"], category: "navigation", status: "ready",
  },
  "micro-interactions/loader-elegant": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      size: "number (optional, default 28) — px",
      color: "string (optional, default accent)",
      className: "string (optional)",
    },
    name: "Loader Elegant",
    description: "Spinner minimale",
    tier: "all", business: ["all"], dependencies: [], category: "micro-interactions", status: "ready",
  },
  "special/announcement-banner": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      text: "string (required)",
      ctaText: "string (optional)",
      ctaHref: "string (optional)",
      dismissible: "boolean (optional, default true)",
      className: "string (optional)",
    },
    name: "Announcement Banner",
    description: "Banner promozionale in alto, chiudibile",
    tier: "all", business: ["all"], dependencies: ["lucide-react"], category: "special", status: "ready",
  },

  /* ─── 24. HOTEL (3) ──────────────────────────────────────────────── */
  "booking/booking-links": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      title: "string (optional, default 'Prenota il tuo soggiorno')",
      description: "string (optional)",
      platforms: "Array<{ name: 'booking'|'expedia'|'trivago'|'hotels'|'airbnb'|'tripadvisor'|'direct'|'custom', url: string, label?: string, badge?: string, highlight?: boolean }> (required)",
      phone: "string (optional) — CTA telefono",
      email: "string (optional) — CTA email",
      layout: "'grid' | 'horizontal' | 'stacked' | 'featured' (optional, default 'grid')",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Booking Links",
    description: "CTA verso portali di prenotazione esterni (Booking, Expedia, ...). Alternativa al calendario.",
    tier: "all",
    business: ["hotel", "all"],
    dependencies: ["lucide-react"],
    category: "booking",
    status: "ready",
  },
  "rooms/room-card": {
    safe: true,
    multiplicity: "collection",
    propsSchema: {
      name: "string (required) — nome camera (es. 'Suite Vista Lago')",
      description: "string (optional)",
      mainImage: "{ src: string, alt: string } (optional)",
      gallery: "Array<{ src: string, alt: string }> (optional) — foto aggiuntive",
      size: "string (optional) — es. '35 m²'",
      maxGuests: "number (optional)",
      features: "string[] (optional) — chip (es. 'Vista lago', 'Balcone')",
      amenities: "Array<{ icon?: string, label: string }> (optional) — icon = nome lucide (Wifi, Coffee, ...)",
      pricePerNight: "number (optional) — € a notte",
      pricePeriod: "string (optional, default '/notte')",
      bookingUrl: "string (optional) — link Booking della camera",
      featured: "boolean (optional) — bordo accent + badge 'Più richiesta'",
      layout: "'card' | 'horizontal' | 'minimal' (optional, default 'card')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Room Card",
    description: "Card camera d'hotel (collection): foto, dimensioni, ospiti, features, prezzo/notte, CTA Booking.",
    tier: "all",
    business: ["hotel", "all"],
    dependencies: ["lucide-react"],
    category: "rooms",
    status: "ready",
  },
  "hotel/hotel-amenities": {
    safe: true,
    multiplicity: "single",
    propsSchema: {
      title: "string (optional, default 'I nostri servizi')",
      description: "string (optional)",
      amenities: "Array<{ name: string, description?: string, icon?: string, image?: { src: string, alt: string } }> (required) — icon = nome lucide",
      layout: "'grid' | 'list' | 'showcase' (optional, default 'grid') — showcase = card con foto",
      columns: "2 | 3 | 4 (optional, default 3)",
      size: "'compact' | 'normal' | 'spacious' (optional, default 'normal')",
      tone: "'modern' | 'classic' | 'editorial' | 'playful' (optional, default 'modern')",
      palette: "{ bg: string, ink: string, accent: string, muted: string } (optional)",
    },
    name: "Hotel Amenities",
    description: "Griglia servizi/amenities dell'hotel (spa, ristorante, parking, wifi). Layout grid/list/showcase.",
    tier: "all",
    business: ["hotel", "all"],
    dependencies: ["lucide-react", "framer-motion"],
    category: "hotel",
    status: "ready",
  },
};

export default LUMINO_LIBRARY;
